OPTION ( BUILD_DEBUG "Build the project using debugging code" OFF )
OPTION ( VERBOSE_BUILD "Verbose build project" OFF )

if(VERBOSE_BUILD)
  SET( CMAKE_VERBOSE_MAKEFILE ON )
endif(VERBOSE_BUILD)

IF( BUILD_DEBUG )
    MESSAGE ( STATUS "---> Build with debug info" )
    set(closure_extra_keys --formatting=PRETTY_PRINT)
    SET( CMAKE_BUILD_TYPE Debug )
    ADD_DEFINITIONS( -DCMS_DEBUG )
    ADD_DEFINITIONS( -g )
    IF(CMS_USE_GCC)
      #ADD_DEFINITIONS( -ftest-coverage )
      ADD_DEFINITIONS( -fprofile-arcs )
      SET(GLOBAL_LINK_LIBS gcov )
    ENDIF(CMS_USE_GCC)
ELSE( BUILD_DEBUG )
    set(lessc_extra_keys --compress)
    IF(UNIX)
        ADD_DEFINITIONS( -O2 )
    ENDIF(UNIX)
ENDIF( BUILD_DEBUG )

IF(UNIX)
    ADD_DEFINITIONS( -Wall )
ENDIF(UNIX)
