#!/bin/bash

dev_root_path="/tmp/docflow"
build_path="${dev_root_path}/build"
console_build_path="${build_path}/console"
ide_build_path="${build_path}/ide"
install_path_release="/mnt/servers/www/var/www/task.sergos.ru"
install_path_debug="/mnt/servers/www/var/www/task-test.sergos.ru"
build_threads=$(($(cat /proc/cpuinfo | grep family | wc -l)+1))
