/* soapzcsPortBindingProxy.h
   Generated by gSOAP 2.7.17 from ./z_soap/z_soap.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapzcsPortBindingProxy_H
#define soapzcsPortBindingProxy_H
#include "soapH.h"
class zcsPortBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'zcsPortBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	zcsPortBinding()
  { soap = soap_new(); endpoint = "http://mail.ordzhonikiwwdze-sanatorium.ru/service/soap/"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns3", "urn:zimbra", NULL, NULL},
	{"ns4", "urn:zimbraAccount", NULL, NULL},
	{"ns5", "urn:zimbraMail", NULL, NULL},
	{"ns6", "urn:zimbraRepl", NULL, NULL},
	{"ns7", "urn:zimbraSync", NULL, NULL},
	{"ns1", "http://www.zimbra.com/wsdl/ZimbraService.wsdl", NULL, NULL},
	{"ns8", "urn:zimbraVoice", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~zcsPortBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'authRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__authRequest(ns4__authRequest *ns4__AuthRequest, ns4__authResponse *ns4__AuthResponse) { return soap ? soap_call___ns1__authRequest(soap, endpoint, NULL, ns4__AuthRequest, ns4__AuthResponse) : SOAP_EOM; };
	/// Invoke 'autoCompleteGalRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__autoCompleteGalRequest(ns4__autoCompleteGalRequest *ns4__AutoCompleteGalRequest, ns4__autoCompleteGalResponse *ns4__AutoCompleteGalResponse) { return soap ? soap_call___ns1__autoCompleteGalRequest(soap, endpoint, NULL, ns4__AutoCompleteGalRequest, ns4__AutoCompleteGalResponse) : SOAP_EOM; };
	/// Invoke 'changePasswordRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__changePasswordRequest(ns4__changePasswordRequest *ns4__ChangePasswordRequest, ns4__changePasswordResponse *ns4__ChangePasswordResponse) { return soap ? soap_call___ns1__changePasswordRequest(soap, endpoint, NULL, ns4__ChangePasswordRequest, ns4__ChangePasswordResponse) : SOAP_EOM; };
	/// Invoke 'checkLicenseRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__checkLicenseRequest(ns4__checkLicenseRequest *ns4__CheckLicenseRequest, ns4__checkLicenseResponse *ns4__CheckLicenseResponse) { return soap ? soap_call___ns1__checkLicenseRequest(soap, endpoint, NULL, ns4__CheckLicenseRequest, ns4__CheckLicenseResponse) : SOAP_EOM; };
	/// Invoke 'checkRightsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__checkRightsRequest(ns4__checkRightsRequest *ns4__CheckRightsRequest, ns4__checkRightsResponse *ns4__CheckRightsResponse) { return soap ? soap_call___ns1__checkRightsRequest(soap, endpoint, NULL, ns4__CheckRightsRequest, ns4__CheckRightsResponse) : SOAP_EOM; };
	/// Invoke 'createDistributionListRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__createDistributionListRequest(ns4__createDistributionListRequest *ns4__CreateDistributionListRequest, ns4__createDistributionListResponse *ns4__CreateDistributionListResponse) { return soap ? soap_call___ns1__createDistributionListRequest(soap, endpoint, NULL, ns4__CreateDistributionListRequest, ns4__CreateDistributionListResponse) : SOAP_EOM; };
	/// Invoke 'createIdentityRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__createIdentityRequest(ns4__createIdentityRequest *ns4__CreateIdentityRequest, ns4__createIdentityResponse *ns4__CreateIdentityResponse) { return soap ? soap_call___ns1__createIdentityRequest(soap, endpoint, NULL, ns4__CreateIdentityRequest, ns4__CreateIdentityResponse) : SOAP_EOM; };
	/// Invoke 'createSignatureRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__createSignatureRequest(ns4__createSignatureRequest *ns4__CreateSignatureRequest, ns4__createSignatureResponse *ns4__CreateSignatureResponse) { return soap ? soap_call___ns1__createSignatureRequest(soap, endpoint, NULL, ns4__CreateSignatureRequest, ns4__CreateSignatureResponse) : SOAP_EOM; };
	/// Invoke 'deleteIdentityRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__deleteIdentityRequest(ns4__deleteIdentityRequest *ns4__DeleteIdentityRequest, ns4__deleteIdentityResponse *ns4__DeleteIdentityResponse) { return soap ? soap_call___ns1__deleteIdentityRequest(soap, endpoint, NULL, ns4__DeleteIdentityRequest, ns4__DeleteIdentityResponse) : SOAP_EOM; };
	/// Invoke 'deleteSignatureRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__deleteSignatureRequest(ns4__deleteSignatureRequest *ns4__DeleteSignatureRequest, ns4__deleteSignatureResponse *ns4__DeleteSignatureResponse) { return soap ? soap_call___ns1__deleteSignatureRequest(soap, endpoint, NULL, ns4__DeleteSignatureRequest, ns4__DeleteSignatureResponse) : SOAP_EOM; };
	/// Invoke 'discoverRightsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__discoverRightsRequest(ns4__discoverRightsRequest *ns4__DiscoverRightsRequest, ns4__discoverRightsResponse *ns4__DiscoverRightsResponse) { return soap ? soap_call___ns1__discoverRightsRequest(soap, endpoint, NULL, ns4__DiscoverRightsRequest, ns4__DiscoverRightsResponse) : SOAP_EOM; };
	/// Invoke 'distributionListActionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__distributionListActionRequest(ns4__distributionListActionRequest *ns4__DistributionListActionRequest, ns4__distributionListActionResponse *ns4__DistributionListActionResponse) { return soap ? soap_call___ns1__distributionListActionRequest(soap, endpoint, NULL, ns4__DistributionListActionRequest, ns4__DistributionListActionResponse) : SOAP_EOM; };
	/// Invoke 'endSessionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__endSessionRequest(ns4__endSessionRequest *ns4__EndSessionRequest, ns4__endSessionResponse *ns4__EndSessionResponse) { return soap ? soap_call___ns1__endSessionRequest(soap, endpoint, NULL, ns4__EndSessionRequest, ns4__EndSessionResponse) : SOAP_EOM; };
	/// Invoke 'getAccountDistributionListsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getAccountDistributionListsRequest(ns4__getAccountDistributionListsRequest *ns4__GetAccountDistributionListsRequest, ns4__getAccountDistributionListsResponse *ns4__GetAccountDistributionListsResponse) { return soap ? soap_call___ns1__getAccountDistributionListsRequest(soap, endpoint, NULL, ns4__GetAccountDistributionListsRequest, ns4__GetAccountDistributionListsResponse) : SOAP_EOM; };
	/// Invoke 'getAccountInfoRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getAccountInfoRequest(ns4__getAccountInfoRequest *ns4__GetAccountInfoRequest, ns4__getAccountInfoResponse *ns4__GetAccountInfoResponse) { return soap ? soap_call___ns1__getAccountInfoRequest(soap, endpoint, NULL, ns4__GetAccountInfoRequest, ns4__GetAccountInfoResponse) : SOAP_EOM; };
	/// Invoke 'getAllLocalesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getAllLocalesRequest(ns4__getAllLocalesRequest *ns4__GetAllLocalesRequest, ns4__getAllLocalesResponse *ns4__GetAllLocalesResponse) { return soap ? soap_call___ns1__getAllLocalesRequest(soap, endpoint, NULL, ns4__GetAllLocalesRequest, ns4__GetAllLocalesResponse) : SOAP_EOM; };
	/// Invoke 'getAvailableCsvFormatsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getAvailableCsvFormatsRequest(ns4__getAvailableCsvFormatsRequest *ns4__GetAvailableCsvFormatsRequest, ns4__getAvailableCsvFormatsResponse *ns4__GetAvailableCsvFormatsResponse) { return soap ? soap_call___ns1__getAvailableCsvFormatsRequest(soap, endpoint, NULL, ns4__GetAvailableCsvFormatsRequest, ns4__GetAvailableCsvFormatsResponse) : SOAP_EOM; };
	/// Invoke 'getAvailableLocalesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getAvailableLocalesRequest(ns4__getAvailableLocalesRequest *ns4__GetAvailableLocalesRequest, ns4__getAvailableLocalesResponse *ns4__GetAvailableLocalesResponse) { return soap ? soap_call___ns1__getAvailableLocalesRequest(soap, endpoint, NULL, ns4__GetAvailableLocalesRequest, ns4__GetAvailableLocalesResponse) : SOAP_EOM; };
	/// Invoke 'getAvailableSkinsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getAvailableSkinsRequest(ns4__getAvailableSkinsRequest *ns4__GetAvailableSkinsRequest, ns4__getAvailableSkinsResponse *ns4__GetAvailableSkinsResponse) { return soap ? soap_call___ns1__getAvailableSkinsRequest(soap, endpoint, NULL, ns4__GetAvailableSkinsRequest, ns4__GetAvailableSkinsResponse) : SOAP_EOM; };
	/// Invoke 'getDistributionListMembersRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getDistributionListMembersRequest(ns4__getDistributionListMembersRequest *ns4__GetDistributionListMembersRequest, ns4__getDistributionListMembersResponse *ns4__GetDistributionListMembersResponse) { return soap ? soap_call___ns1__getDistributionListMembersRequest(soap, endpoint, NULL, ns4__GetDistributionListMembersRequest, ns4__GetDistributionListMembersResponse) : SOAP_EOM; };
	/// Invoke 'getDistributionListRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getDistributionListRequest(ns4__getDistributionListRequest *ns4__GetDistributionListRequest, ns4__getDistributionListResponse *ns4__GetDistributionListResponse) { return soap ? soap_call___ns1__getDistributionListRequest(soap, endpoint, NULL, ns4__GetDistributionListRequest, ns4__GetDistributionListResponse) : SOAP_EOM; };
	/// Invoke 'getIdentitiesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getIdentitiesRequest(ns4__getIdentitiesRequest *ns4__GetIdentitiesRequest, ns4__getIdentitiesResponse *ns4__GetIdentitiesResponse) { return soap ? soap_call___ns1__getIdentitiesRequest(soap, endpoint, NULL, ns4__GetIdentitiesRequest, ns4__GetIdentitiesResponse) : SOAP_EOM; };
	/// Invoke 'getInfoRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getInfoRequest(ns4__getInfoRequest *ns4__GetInfoRequest, ns4__getInfoResponse *ns4__GetInfoResponse) { return soap ? soap_call___ns1__getInfoRequest(soap, endpoint, NULL, ns4__GetInfoRequest, ns4__GetInfoResponse) : SOAP_EOM; };
	/// Invoke 'getPrefsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getPrefsRequest(ns4__getPrefsRequest *ns4__GetPrefsRequest, ns4__getPrefsResponse *ns4__GetPrefsResponse) { return soap ? soap_call___ns1__getPrefsRequest(soap, endpoint, NULL, ns4__GetPrefsRequest, ns4__GetPrefsResponse) : SOAP_EOM; };
	/// Invoke 'getRightsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getRightsRequest(ns4__getRightsRequest *ns4__GetRightsRequest, ns4__getRightsResponse *ns4__GetRightsResponse) { return soap ? soap_call___ns1__getRightsRequest(soap, endpoint, NULL, ns4__GetRightsRequest, ns4__GetRightsResponse) : SOAP_EOM; };
	/// Invoke 'getSMIMEPublicCertsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getSMIMEPublicCertsRequest(ns4__getSMIMEPublicCertsRequest *ns4__GetSMIMEPublicCertsRequest, ns4__getSMIMEPublicCertsResponse *ns4__GetSMIMEPublicCertsResponse) { return soap ? soap_call___ns1__getSMIMEPublicCertsRequest(soap, endpoint, NULL, ns4__GetSMIMEPublicCertsRequest, ns4__GetSMIMEPublicCertsResponse) : SOAP_EOM; };
	/// Invoke 'getShareInfoRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getShareInfoRequest(ns4__getShareInfoRequest *ns4__GetShareInfoRequest, ns4__getShareInfoResponse *ns4__GetShareInfoResponse) { return soap ? soap_call___ns1__getShareInfoRequest(soap, endpoint, NULL, ns4__GetShareInfoRequest, ns4__GetShareInfoResponse) : SOAP_EOM; };
	/// Invoke 'getSignaturesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getSignaturesRequest(ns4__getSignaturesRequest *ns4__GetSignaturesRequest, ns4__getSignaturesResponse *ns4__GetSignaturesResponse) { return soap ? soap_call___ns1__getSignaturesRequest(soap, endpoint, NULL, ns4__GetSignaturesRequest, ns4__GetSignaturesResponse) : SOAP_EOM; };
	/// Invoke 'getVersionInfoRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getVersionInfoRequest(ns4__getVersionInfoRequest *ns4__GetVersionInfoRequest, ns4__getVersionInfoResponse *ns4__GetVersionInfoResponse) { return soap ? soap_call___ns1__getVersionInfoRequest(soap, endpoint, NULL, ns4__GetVersionInfoRequest, ns4__GetVersionInfoResponse) : SOAP_EOM; };
	/// Invoke 'getWhiteBlackListRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getWhiteBlackListRequest(ns4__getWhiteBlackListRequest *ns4__GetWhiteBlackListRequest, ns4__getWhiteBlackListResponse *ns4__GetWhiteBlackListResponse) { return soap ? soap_call___ns1__getWhiteBlackListRequest(soap, endpoint, NULL, ns4__GetWhiteBlackListRequest, ns4__GetWhiteBlackListResponse) : SOAP_EOM; };
	/// Invoke 'grantRightsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__grantRightsRequest(ns4__grantRightsRequest *ns4__GrantRightsRequest, ns4__grantRightsResponse *ns4__GrantRightsResponse) { return soap ? soap_call___ns1__grantRightsRequest(soap, endpoint, NULL, ns4__GrantRightsRequest, ns4__GrantRightsResponse) : SOAP_EOM; };
	/// Invoke 'modifyIdentityRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifyIdentityRequest(ns4__modifyIdentityRequest *ns4__ModifyIdentityRequest, ns4__modifyIdentityResponse *ns4__ModifyIdentityResponse) { return soap ? soap_call___ns1__modifyIdentityRequest(soap, endpoint, NULL, ns4__ModifyIdentityRequest, ns4__ModifyIdentityResponse) : SOAP_EOM; };
	/// Invoke 'modifyPrefsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifyPrefsRequest(ns4__modifyPrefsRequest *ns4__ModifyPrefsRequest, ns4__modifyPrefsResponse *ns4__ModifyPrefsResponse) { return soap ? soap_call___ns1__modifyPrefsRequest(soap, endpoint, NULL, ns4__ModifyPrefsRequest, ns4__ModifyPrefsResponse) : SOAP_EOM; };
	/// Invoke 'modifyPropertiesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifyPropertiesRequest(ns4__modifyPropertiesRequest *ns4__ModifyPropertiesRequest, ns4__modifyPropertiesResponse *ns4__ModifyPropertiesResponse) { return soap ? soap_call___ns1__modifyPropertiesRequest(soap, endpoint, NULL, ns4__ModifyPropertiesRequest, ns4__ModifyPropertiesResponse) : SOAP_EOM; };
	/// Invoke 'modifySignatureRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifySignatureRequest(ns4__modifySignatureRequest *ns4__ModifySignatureRequest, ns4__modifySignatureResponse *ns4__ModifySignatureResponse) { return soap ? soap_call___ns1__modifySignatureRequest(soap, endpoint, NULL, ns4__ModifySignatureRequest, ns4__ModifySignatureResponse) : SOAP_EOM; };
	/// Invoke 'modifyWhiteBlackListRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifyWhiteBlackListRequest(ns4__modifyWhiteBlackListRequest *ns4__ModifyWhiteBlackListRequest, ns4__modifyWhiteBlackListResponse *ns4__ModifyWhiteBlackListResponse) { return soap ? soap_call___ns1__modifyWhiteBlackListRequest(soap, endpoint, NULL, ns4__ModifyWhiteBlackListRequest, ns4__ModifyWhiteBlackListResponse) : SOAP_EOM; };
	/// Invoke 'modifyZimletPrefsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifyZimletPrefsRequest(ns4__modifyZimletPrefsRequest *ns4__ModifyZimletPrefsRequest, ns4__modifyZimletPrefsResponse *ns4__ModifyZimletPrefsResponse) { return soap ? soap_call___ns1__modifyZimletPrefsRequest(soap, endpoint, NULL, ns4__ModifyZimletPrefsRequest, ns4__ModifyZimletPrefsResponse) : SOAP_EOM; };
	/// Invoke 'revokeRightsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__revokeRightsRequest(ns4__revokeRightsRequest *ns4__RevokeRightsRequest, ns4__revokeRightsResponse *ns4__RevokeRightsResponse) { return soap ? soap_call___ns1__revokeRightsRequest(soap, endpoint, NULL, ns4__RevokeRightsRequest, ns4__RevokeRightsResponse) : SOAP_EOM; };
	/// Invoke 'searchCalendarResourcesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__searchCalendarResourcesRequest(ns4__searchCalendarResourcesRequest *ns4__SearchCalendarResourcesRequest, ns4__searchCalendarResourcesResponse *ns4__SearchCalendarResourcesResponse) { return soap ? soap_call___ns1__searchCalendarResourcesRequest(soap, endpoint, NULL, ns4__SearchCalendarResourcesRequest, ns4__SearchCalendarResourcesResponse) : SOAP_EOM; };
	/// Invoke 'searchGalRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__searchGalRequest(ns4__searchGalRequest *ns4__SearchGalRequest, ns4__searchGalResponse *ns4__SearchGalResponse) { return soap ? soap_call___ns1__searchGalRequest(soap, endpoint, NULL, ns4__SearchGalRequest, ns4__SearchGalResponse) : SOAP_EOM; };
	/// Invoke 'subscribeDistributionListRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__subscribeDistributionListRequest(ns4__subscribeDistributionListRequest *ns4__SubscribeDistributionListRequest, ns4__subscribeDistributionListResponse *ns4__SubscribeDistributionListResponse) { return soap ? soap_call___ns1__subscribeDistributionListRequest(soap, endpoint, NULL, ns4__SubscribeDistributionListRequest, ns4__SubscribeDistributionListResponse) : SOAP_EOM; };
	/// Invoke 'syncGalRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__syncGalRequest(ns4__syncGalRequest *ns4__SyncGalRequest, ns4__syncGalResponse *ns4__SyncGalResponse) { return soap ? soap_call___ns1__syncGalRequest(soap, endpoint, NULL, ns4__SyncGalRequest, ns4__SyncGalResponse) : SOAP_EOM; };
	/// Invoke 'addAppointmentInviteRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__addAppointmentInviteRequest(ns5__addAppointmentInviteRequest *ns5__AddAppointmentInviteRequest, ns5__addAppointmentInviteResponse *ns5__AddAppointmentInviteResponse) { return soap ? soap_call___ns1__addAppointmentInviteRequest(soap, endpoint, NULL, ns5__AddAppointmentInviteRequest, ns5__AddAppointmentInviteResponse) : SOAP_EOM; };
	/// Invoke 'addCommentRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__addCommentRequest(ns5__addCommentRequest *ns5__AddCommentRequest, ns5__addCommentResponse *ns5__AddCommentResponse) { return soap ? soap_call___ns1__addCommentRequest(soap, endpoint, NULL, ns5__AddCommentRequest, ns5__AddCommentResponse) : SOAP_EOM; };
	/// Invoke 'addMsgRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__addMsgRequest(ns5__addMsgRequest *ns5__AddMsgRequest, ns5__addMsgResponse *ns5__AddMsgResponse) { return soap ? soap_call___ns1__addMsgRequest(soap, endpoint, NULL, ns5__AddMsgRequest, ns5__AddMsgResponse) : SOAP_EOM; };
	/// Invoke 'addTaskInviteRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__addTaskInviteRequest(ns5__addTaskInviteRequest *ns5__AddTaskInviteRequest, ns5__addTaskInviteResponse *ns5__AddTaskInviteResponse) { return soap ? soap_call___ns1__addTaskInviteRequest(soap, endpoint, NULL, ns5__AddTaskInviteRequest, ns5__AddTaskInviteResponse) : SOAP_EOM; };
	/// Invoke 'announceOrganizerChangeRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__announceOrganizerChangeRequest(ns5__announceOrganizerChangeRequest *ns5__AnnounceOrganizerChangeRequest, ns5__announceOrganizerChangeResponse *ns5__AnnounceOrganizerChangeResponse) { return soap ? soap_call___ns1__announceOrganizerChangeRequest(soap, endpoint, NULL, ns5__AnnounceOrganizerChangeRequest, ns5__AnnounceOrganizerChangeResponse) : SOAP_EOM; };
	/// Invoke 'applyFilterRulesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__applyFilterRulesRequest(ns5__applyFilterRulesRequest *ns5__ApplyFilterRulesRequest, ns5__applyFilterRulesResponse *ns5__ApplyFilterRulesResponse) { return soap ? soap_call___ns1__applyFilterRulesRequest(soap, endpoint, NULL, ns5__ApplyFilterRulesRequest, ns5__ApplyFilterRulesResponse) : SOAP_EOM; };
	/// Invoke 'applyOutgoingFilterRulesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__applyOutgoingFilterRulesRequest(ns5__applyOutgoingFilterRulesRequest *ns5__ApplyOutgoingFilterRulesRequest, ns5__applyOutgoingFilterRulesResponse *ns5__ApplyOutgoingFilterRulesResponse) { return soap ? soap_call___ns1__applyOutgoingFilterRulesRequest(soap, endpoint, NULL, ns5__ApplyOutgoingFilterRulesRequest, ns5__ApplyOutgoingFilterRulesResponse) : SOAP_EOM; };
	/// Invoke 'autoCompleteRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__autoCompleteRequest(ns5__autoCompleteRequest *ns5__AutoCompleteRequest, ns5__autoCompleteResponse *ns5__AutoCompleteResponse) { return soap ? soap_call___ns1__autoCompleteRequest(soap, endpoint, NULL, ns5__AutoCompleteRequest, ns5__AutoCompleteResponse) : SOAP_EOM; };
	/// Invoke 'bounceMsgRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__bounceMsgRequest(ns5__bounceMsgRequest *ns5__BounceMsgRequest, ns5__bounceMsgResponse *ns5__BounceMsgResponse) { return soap ? soap_call___ns1__bounceMsgRequest(soap, endpoint, NULL, ns5__BounceMsgRequest, ns5__BounceMsgResponse) : SOAP_EOM; };
	/// Invoke 'browseRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__browseRequest(ns5__browseRequest *ns5__BrowseRequest, ns5__browseResponse *ns5__BrowseResponse) { return soap ? soap_call___ns1__browseRequest(soap, endpoint, NULL, ns5__BrowseRequest, ns5__BrowseResponse) : SOAP_EOM; };
	/// Invoke 'cancelAppointmentRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__cancelAppointmentRequest(ns5__cancelAppointmentRequest *ns5__CancelAppointmentRequest, ns5__cancelAppointmentResponse *ns5__CancelAppointmentResponse) { return soap ? soap_call___ns1__cancelAppointmentRequest(soap, endpoint, NULL, ns5__CancelAppointmentRequest, ns5__CancelAppointmentResponse) : SOAP_EOM; };
	/// Invoke 'cancelTaskRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__cancelTaskRequest(ns5__cancelTaskRequest *ns5__CancelTaskRequest, ns5__cancelTaskResponse *ns5__CancelTaskResponse) { return soap ? soap_call___ns1__cancelTaskRequest(soap, endpoint, NULL, ns5__CancelTaskRequest, ns5__CancelTaskResponse) : SOAP_EOM; };
	/// Invoke 'checkDeviceStatusRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__checkDeviceStatusRequest(ns5__checkDeviceStatusRequest *ns5__CheckDeviceStatusRequest, ns5__checkDeviceStatusResponse *ns5__CheckDeviceStatusResponse) { return soap ? soap_call___ns1__checkDeviceStatusRequest(soap, endpoint, NULL, ns5__CheckDeviceStatusRequest, ns5__CheckDeviceStatusResponse) : SOAP_EOM; };
	/// Invoke 'checkPermissionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__checkPermissionRequest(ns5__checkPermissionRequest *ns5__CheckPermissionRequest, ns5__checkPermissionResponse *ns5__CheckPermissionResponse) { return soap ? soap_call___ns1__checkPermissionRequest(soap, endpoint, NULL, ns5__CheckPermissionRequest, ns5__CheckPermissionResponse) : SOAP_EOM; };
	/// Invoke 'checkRecurConflictsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__checkRecurConflictsRequest(ns5__checkRecurConflictsRequest *ns5__CheckRecurConflictsRequest, ns5__checkRecurConflictsResponse *ns5__CheckRecurConflictsResponse) { return soap ? soap_call___ns1__checkRecurConflictsRequest(soap, endpoint, NULL, ns5__CheckRecurConflictsRequest, ns5__CheckRecurConflictsResponse) : SOAP_EOM; };
	/// Invoke 'checkSpellingRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__checkSpellingRequest(ns5__checkSpellingRequest *ns5__CheckSpellingRequest, ns5__checkSpellingResponse *ns5__CheckSpellingResponse) { return soap ? soap_call___ns1__checkSpellingRequest(soap, endpoint, NULL, ns5__CheckSpellingRequest, ns5__CheckSpellingResponse) : SOAP_EOM; };
	/// Invoke 'completeTaskInstanceRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__completeTaskInstanceRequest(ns5__completeTaskInstanceRequest *ns5__CompleteTaskInstanceRequest, ns5__completeTaskInstanceResponse *ns5__CompleteTaskInstanceResponse) { return soap ? soap_call___ns1__completeTaskInstanceRequest(soap, endpoint, NULL, ns5__CompleteTaskInstanceRequest, ns5__CompleteTaskInstanceResponse) : SOAP_EOM; };
	/// Invoke 'contactActionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__contactActionRequest(ns5__contactActionRequest *ns5__ContactActionRequest, ns5__contactActionResponse *ns5__ContactActionResponse) { return soap ? soap_call___ns1__contactActionRequest(soap, endpoint, NULL, ns5__ContactActionRequest, ns5__ContactActionResponse) : SOAP_EOM; };
	/// Invoke 'convActionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__convActionRequest(ns5__convActionRequest *ns5__ConvActionRequest, ns5__convActionResponse *ns5__ConvActionResponse) { return soap ? soap_call___ns1__convActionRequest(soap, endpoint, NULL, ns5__ConvActionRequest, ns5__ConvActionResponse) : SOAP_EOM; };
	/// Invoke 'counterAppointmentRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__counterAppointmentRequest(ns5__counterAppointmentRequest *ns5__CounterAppointmentRequest, ns5__counterAppointmentResponse *ns5__CounterAppointmentResponse) { return soap ? soap_call___ns1__counterAppointmentRequest(soap, endpoint, NULL, ns5__CounterAppointmentRequest, ns5__CounterAppointmentResponse) : SOAP_EOM; };
	/// Invoke 'createAppointmentExceptionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__createAppointmentExceptionRequest(ns5__createAppointmentExceptionRequest *ns5__CreateAppointmentExceptionRequest, ns5__createAppointmentExceptionResponse *ns5__CreateAppointmentExceptionResponse) { return soap ? soap_call___ns1__createAppointmentExceptionRequest(soap, endpoint, NULL, ns5__CreateAppointmentExceptionRequest, ns5__CreateAppointmentExceptionResponse) : SOAP_EOM; };
	/// Invoke 'createAppointmentRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__createAppointmentRequest(ns5__createAppointmentRequest *ns5__CreateAppointmentRequest, ns5__createAppointmentResponse *ns5__CreateAppointmentResponse) { return soap ? soap_call___ns1__createAppointmentRequest(soap, endpoint, NULL, ns5__CreateAppointmentRequest, ns5__CreateAppointmentResponse) : SOAP_EOM; };
	/// Invoke 'createContactRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__createContactRequest(ns5__createContactRequest *ns5__CreateContactRequest, ns5__createContactResponse *ns5__CreateContactResponse) { return soap ? soap_call___ns1__createContactRequest(soap, endpoint, NULL, ns5__CreateContactRequest, ns5__CreateContactResponse) : SOAP_EOM; };
	/// Invoke 'createDataSourceRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__createDataSourceRequest(ns5__createDataSourceRequest *ns5__CreateDataSourceRequest, ns5__createDataSourceResponse *ns5__CreateDataSourceResponse) { return soap ? soap_call___ns1__createDataSourceRequest(soap, endpoint, NULL, ns5__CreateDataSourceRequest, ns5__CreateDataSourceResponse) : SOAP_EOM; };
	/// Invoke 'createFolderRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__createFolderRequest(ns5__createFolderRequest *ns5__CreateFolderRequest, ns5__createFolderResponse *ns5__CreateFolderResponse) { return soap ? soap_call___ns1__createFolderRequest(soap, endpoint, NULL, ns5__CreateFolderRequest, ns5__CreateFolderResponse) : SOAP_EOM; };
	/// Invoke 'createMountpointRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__createMountpointRequest(ns5__createMountpointRequest *ns5__CreateMountpointRequest, ns5__createMountpointResponse *ns5__CreateMountpointResponse) { return soap ? soap_call___ns1__createMountpointRequest(soap, endpoint, NULL, ns5__CreateMountpointRequest, ns5__CreateMountpointResponse) : SOAP_EOM; };
	/// Invoke 'createNoteRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__createNoteRequest(ns5__createNoteRequest *ns5__CreateNoteRequest, ns5__createNoteResponse *ns5__CreateNoteResponse) { return soap ? soap_call___ns1__createNoteRequest(soap, endpoint, NULL, ns5__CreateNoteRequest, ns5__CreateNoteResponse) : SOAP_EOM; };
	/// Invoke 'createSearchFolderRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__createSearchFolderRequest(ns5__createSearchFolderRequest *ns5__CreateSearchFolderRequest, ns5__createSearchFolderResponse *ns5__CreateSearchFolderResponse) { return soap ? soap_call___ns1__createSearchFolderRequest(soap, endpoint, NULL, ns5__CreateSearchFolderRequest, ns5__CreateSearchFolderResponse) : SOAP_EOM; };
	/// Invoke 'createTagRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__createTagRequest(ns5__createTagRequest *ns5__CreateTagRequest, ns5__createTagResponse *ns5__CreateTagResponse) { return soap ? soap_call___ns1__createTagRequest(soap, endpoint, NULL, ns5__CreateTagRequest, ns5__CreateTagResponse) : SOAP_EOM; };
	/// Invoke 'createTaskExceptionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__createTaskExceptionRequest(ns5__createTaskExceptionRequest *ns5__CreateTaskExceptionRequest, ns5__createTaskExceptionResponse *ns5__CreateTaskExceptionResponse) { return soap ? soap_call___ns1__createTaskExceptionRequest(soap, endpoint, NULL, ns5__CreateTaskExceptionRequest, ns5__CreateTaskExceptionResponse) : SOAP_EOM; };
	/// Invoke 'createTaskRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__createTaskRequest(ns5__createTaskRequest *ns5__CreateTaskRequest, ns5__createTaskResponse *ns5__CreateTaskResponse) { return soap ? soap_call___ns1__createTaskRequest(soap, endpoint, NULL, ns5__CreateTaskRequest, ns5__CreateTaskResponse) : SOAP_EOM; };
	/// Invoke 'createWaitSetRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__createWaitSetRequest(ns5__createWaitSetRequest *ns5__CreateWaitSetRequest, ns5__createWaitSetResponse *ns5__CreateWaitSetResponse) { return soap ? soap_call___ns1__createWaitSetRequest(soap, endpoint, NULL, ns5__CreateWaitSetRequest, ns5__CreateWaitSetResponse) : SOAP_EOM; };
	/// Invoke 'declineCounterAppointmentRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__declineCounterAppointmentRequest(ns5__declineCounterAppointmentRequest *ns5__DeclineCounterAppointmentRequest, ns5__declineCounterAppointmentResponse *ns5__DeclineCounterAppointmentResponse) { return soap ? soap_call___ns1__declineCounterAppointmentRequest(soap, endpoint, NULL, ns5__DeclineCounterAppointmentRequest, ns5__DeclineCounterAppointmentResponse) : SOAP_EOM; };
	/// Invoke 'deleteDataSourceRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__deleteDataSourceRequest(ns5__deleteDataSourceRequest *ns5__DeleteDataSourceRequest, ns5__deleteDataSourceResponse *ns5__DeleteDataSourceResponse) { return soap ? soap_call___ns1__deleteDataSourceRequest(soap, endpoint, NULL, ns5__DeleteDataSourceRequest, ns5__DeleteDataSourceResponse) : SOAP_EOM; };
	/// Invoke 'deleteDeviceRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__deleteDeviceRequest(ns5__deleteDeviceRequest *ns5__DeleteDeviceRequest, ns5__deleteDeviceResponse *ns5__DeleteDeviceResponse) { return soap ? soap_call___ns1__deleteDeviceRequest(soap, endpoint, NULL, ns5__DeleteDeviceRequest, ns5__DeleteDeviceResponse) : SOAP_EOM; };
	/// Invoke 'destroyWaitSetRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__destroyWaitSetRequest(ns5__destroyWaitSetRequest *ns5__DestroyWaitSetRequest, ns5__destroyWaitSetResponse *ns5__DestroyWaitSetResponse) { return soap ? soap_call___ns1__destroyWaitSetRequest(soap, endpoint, NULL, ns5__DestroyWaitSetRequest, ns5__DestroyWaitSetResponse) : SOAP_EOM; };
	/// Invoke 'diffDocumentRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__diffDocumentRequest(ns5__diffDocumentRequest *ns5__DiffDocumentRequest, ns5__diffDocumentResponse *ns5__DiffDocumentResponse) { return soap ? soap_call___ns1__diffDocumentRequest(soap, endpoint, NULL, ns5__DiffDocumentRequest, ns5__DiffDocumentResponse) : SOAP_EOM; };
	/// Invoke 'dismissCalendarItemAlarmRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__dismissCalendarItemAlarmRequest(ns5__dismissCalendarItemAlarmRequest *ns5__DismissCalendarItemAlarmRequest, ns5__dismissCalendarItemAlarmResponse *ns5__DismissCalendarItemAlarmResponse) { return soap ? soap_call___ns1__dismissCalendarItemAlarmRequest(soap, endpoint, NULL, ns5__DismissCalendarItemAlarmRequest, ns5__DismissCalendarItemAlarmResponse) : SOAP_EOM; };
	/// Invoke 'documentActionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__documentActionRequest(ns5__documentActionRequest *ns5__DocumentActionRequest, ns5__documentActionResponse *ns5__DocumentActionResponse) { return soap ? soap_call___ns1__documentActionRequest(soap, endpoint, NULL, ns5__DocumentActionRequest, ns5__DocumentActionResponse) : SOAP_EOM; };
	/// Invoke 'emptyDumpsterRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__emptyDumpsterRequest(ns5__emptyDumpsterRequest *ns5__EmptyDumpsterRequest, ns5__emptyDumpsterResponse *ns5__EmptyDumpsterResponse) { return soap ? soap_call___ns1__emptyDumpsterRequest(soap, endpoint, NULL, ns5__EmptyDumpsterRequest, ns5__EmptyDumpsterResponse) : SOAP_EOM; };
	/// Invoke 'enableSharedReminderRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__enableSharedReminderRequest(ns5__enableSharedReminderRequest *ns5__EnableSharedReminderRequest, ns5__enableSharedReminderResponse *ns5__EnableSharedReminderResponse) { return soap ? soap_call___ns1__enableSharedReminderRequest(soap, endpoint, NULL, ns5__EnableSharedReminderRequest, ns5__EnableSharedReminderResponse) : SOAP_EOM; };
	/// Invoke 'expandRecurRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__expandRecurRequest(ns5__expandRecurRequest *ns5__ExpandRecurRequest, ns5__expandRecurResponse *ns5__ExpandRecurResponse) { return soap ? soap_call___ns1__expandRecurRequest(soap, endpoint, NULL, ns5__ExpandRecurRequest, ns5__ExpandRecurResponse) : SOAP_EOM; };
	/// Invoke 'exportContactsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__exportContactsRequest(ns5__exportContactsRequest *ns5__ExportContactsRequest, ns5__exportContactsResponse *ns5__ExportContactsResponse) { return soap ? soap_call___ns1__exportContactsRequest(soap, endpoint, NULL, ns5__ExportContactsRequest, ns5__ExportContactsResponse) : SOAP_EOM; };
	/// Invoke 'folderActionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__folderActionRequest(ns5__folderActionRequest *ns5__FolderActionRequest, ns5__folderActionResponse *ns5__FolderActionResponse) { return soap ? soap_call___ns1__folderActionRequest(soap, endpoint, NULL, ns5__FolderActionRequest, ns5__FolderActionResponse) : SOAP_EOM; };
	/// Invoke 'forwardAppointmentInviteRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__forwardAppointmentInviteRequest(ns5__forwardAppointmentInviteRequest *ns5__ForwardAppointmentInviteRequest, ns5__forwardAppointmentInviteResponse *ns5__ForwardAppointmentInviteResponse) { return soap ? soap_call___ns1__forwardAppointmentInviteRequest(soap, endpoint, NULL, ns5__ForwardAppointmentInviteRequest, ns5__ForwardAppointmentInviteResponse) : SOAP_EOM; };
	/// Invoke 'forwardAppointmentRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__forwardAppointmentRequest(ns5__forwardAppointmentRequest *ns5__ForwardAppointmentRequest, ns5__forwardAppointmentResponse *ns5__ForwardAppointmentResponse) { return soap ? soap_call___ns1__forwardAppointmentRequest(soap, endpoint, NULL, ns5__ForwardAppointmentRequest, ns5__ForwardAppointmentResponse) : SOAP_EOM; };
	/// Invoke 'generateUUIDRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__generateUUIDRequest(ns5__generateUUIDRequest *ns5__GenerateUUIDRequest, std::string &ns5__GenerateUUIDResponse) { return soap ? soap_call___ns1__generateUUIDRequest(soap, endpoint, NULL, ns5__GenerateUUIDRequest, ns5__GenerateUUIDResponse) : SOAP_EOM; };
	/// Invoke 'getActivityStreamRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getActivityStreamRequest(ns5__getActivityStreamRequest *ns5__GetActivityStreamRequest, ns5__getActivityStreamResponse *ns5__GetActivityStreamResponse) { return soap ? soap_call___ns1__getActivityStreamRequest(soap, endpoint, NULL, ns5__GetActivityStreamRequest, ns5__GetActivityStreamResponse) : SOAP_EOM; };
	/// Invoke 'getAllDevicesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getAllDevicesRequest(ns5__getAllDevicesRequest *ns5__GetAllDevicesRequest, ns5__getAllDevicesResponse *ns5__GetAllDevicesResponse) { return soap ? soap_call___ns1__getAllDevicesRequest(soap, endpoint, NULL, ns5__GetAllDevicesRequest, ns5__GetAllDevicesResponse) : SOAP_EOM; };
	/// Invoke 'getAppointmentRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getAppointmentRequest(ns5__getAppointmentRequest *ns5__GetAppointmentRequest, ns5__getAppointmentResponse *ns5__GetAppointmentResponse) { return soap ? soap_call___ns1__getAppointmentRequest(soap, endpoint, NULL, ns5__GetAppointmentRequest, ns5__GetAppointmentResponse) : SOAP_EOM; };
	/// Invoke 'getApptSummariesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getApptSummariesRequest(ns5__getApptSummariesRequest *ns5__GetApptSummariesRequest, ns5__getApptSummariesResponse *ns5__GetApptSummariesResponse) { return soap ? soap_call___ns1__getApptSummariesRequest(soap, endpoint, NULL, ns5__GetApptSummariesRequest, ns5__GetApptSummariesResponse) : SOAP_EOM; };
	/// Invoke 'getCalendarItemSummariesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getCalendarItemSummariesRequest(ns5__getCalendarItemSummariesRequest *ns5__GetCalendarItemSummariesRequest, ns5__getCalendarItemSummariesResponse *ns5__GetCalendarItemSummariesResponse) { return soap ? soap_call___ns1__getCalendarItemSummariesRequest(soap, endpoint, NULL, ns5__GetCalendarItemSummariesRequest, ns5__GetCalendarItemSummariesResponse) : SOAP_EOM; };
	/// Invoke 'getCommentsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getCommentsRequest(ns5__getCommentsRequest *ns5__GetCommentsRequest, ns5__getCommentsResponse *ns5__GetCommentsResponse) { return soap ? soap_call___ns1__getCommentsRequest(soap, endpoint, NULL, ns5__GetCommentsRequest, ns5__GetCommentsResponse) : SOAP_EOM; };
	/// Invoke 'getContactsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getContactsRequest(ns5__getContactsRequest *ns5__GetContactsRequest, ns5__getContactsResponse *ns5__GetContactsResponse) { return soap ? soap_call___ns1__getContactsRequest(soap, endpoint, NULL, ns5__GetContactsRequest, ns5__GetContactsResponse) : SOAP_EOM; };
	/// Invoke 'getConvRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getConvRequest(ns5__getConvRequest *ns5__GetConvRequest, ns5__getConvResponse *ns5__GetConvResponse) { return soap ? soap_call___ns1__getConvRequest(soap, endpoint, NULL, ns5__GetConvRequest, ns5__GetConvResponse) : SOAP_EOM; };
	/// Invoke 'getCustomMetadataRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getCustomMetadataRequest(ns5__getCustomMetadataRequest *ns5__GetCustomMetadataRequest, ns5__getCustomMetadataResponse *ns5__GetCustomMetadataResponse) { return soap ? soap_call___ns1__getCustomMetadataRequest(soap, endpoint, NULL, ns5__GetCustomMetadataRequest, ns5__GetCustomMetadataResponse) : SOAP_EOM; };
	/// Invoke 'getDataSourcesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getDataSourcesRequest(ns5__getDataSourcesRequest *ns5__GetDataSourcesRequest, ns5__getDataSourcesResponse *ns5__GetDataSourcesResponse) { return soap ? soap_call___ns1__getDataSourcesRequest(soap, endpoint, NULL, ns5__GetDataSourcesRequest, ns5__GetDataSourcesResponse) : SOAP_EOM; };
	/// Invoke 'getDocumentShareURLRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getDocumentShareURLRequest(ns5__getDocumentShareURLRequest *ns5__GetDocumentShareURLRequest, std::string &ns5__GetDocumentShareURLResponse) { return soap ? soap_call___ns1__getDocumentShareURLRequest(soap, endpoint, NULL, ns5__GetDocumentShareURLRequest, ns5__GetDocumentShareURLResponse) : SOAP_EOM; };
	/// Invoke 'getEffectiveFolderPermsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getEffectiveFolderPermsRequest(ns5__getEffectiveFolderPermsRequest *ns5__GetEffectiveFolderPermsRequest, ns5__getEffectiveFolderPermsResponse *ns5__GetEffectiveFolderPermsResponse) { return soap ? soap_call___ns1__getEffectiveFolderPermsRequest(soap, endpoint, NULL, ns5__GetEffectiveFolderPermsRequest, ns5__GetEffectiveFolderPermsResponse) : SOAP_EOM; };
	/// Invoke 'getFilterRulesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getFilterRulesRequest(ns5__getFilterRulesRequest *ns5__GetFilterRulesRequest, ns5__getFilterRulesResponse *ns5__GetFilterRulesResponse) { return soap ? soap_call___ns1__getFilterRulesRequest(soap, endpoint, NULL, ns5__GetFilterRulesRequest, ns5__GetFilterRulesResponse) : SOAP_EOM; };
	/// Invoke 'getFolderRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getFolderRequest(ns5__getFolderRequest *ns5__GetFolderRequest, ns5__getFolderResponse *ns5__GetFolderResponse) { return soap ? soap_call___ns1__getFolderRequest(soap, endpoint, NULL, ns5__GetFolderRequest, ns5__GetFolderResponse) : SOAP_EOM; };
	/// Invoke 'getFreeBusyRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getFreeBusyRequest(ns5__getFreeBusyRequest *ns5__GetFreeBusyRequest, ns5__getFreeBusyResponse *ns5__GetFreeBusyResponse) { return soap ? soap_call___ns1__getFreeBusyRequest(soap, endpoint, NULL, ns5__GetFreeBusyRequest, ns5__GetFreeBusyResponse) : SOAP_EOM; };
	/// Invoke 'getICalRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getICalRequest(ns5__getICalRequest *ns5__GetICalRequest, ns5__getICalResponse *ns5__GetICalResponse) { return soap ? soap_call___ns1__getICalRequest(soap, endpoint, NULL, ns5__GetICalRequest, ns5__GetICalResponse) : SOAP_EOM; };
	/// Invoke 'getImportStatusRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getImportStatusRequest(ns5__getImportStatusRequest *ns5__GetImportStatusRequest, ns5__getImportStatusResponse *ns5__GetImportStatusResponse) { return soap ? soap_call___ns1__getImportStatusRequest(soap, endpoint, NULL, ns5__GetImportStatusRequest, ns5__GetImportStatusResponse) : SOAP_EOM; };
	/// Invoke 'getItemRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getItemRequest(ns5__getItemRequest *ns5__GetItemRequest, ns5__getItemResponse *ns5__GetItemResponse) { return soap ? soap_call___ns1__getItemRequest(soap, endpoint, NULL, ns5__GetItemRequest, ns5__GetItemResponse) : SOAP_EOM; };
	/// Invoke 'getMailboxMetadataRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getMailboxMetadataRequest(ns5__getMailboxMetadataRequest *ns5__GetMailboxMetadataRequest, ns5__getMailboxMetadataResponse *ns5__GetMailboxMetadataResponse) { return soap ? soap_call___ns1__getMailboxMetadataRequest(soap, endpoint, NULL, ns5__GetMailboxMetadataRequest, ns5__GetMailboxMetadataResponse) : SOAP_EOM; };
	/// Invoke 'getMiniCalRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getMiniCalRequest(ns5__getMiniCalRequest *ns5__GetMiniCalRequest, ns5__getMiniCalResponse *ns5__GetMiniCalResponse) { return soap ? soap_call___ns1__getMiniCalRequest(soap, endpoint, NULL, ns5__GetMiniCalRequest, ns5__GetMiniCalResponse) : SOAP_EOM; };
	/// Invoke 'getMsgMetadataRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getMsgMetadataRequest(ns5__getMsgMetadataRequest *ns5__GetMsgMetadataRequest, ns5__getMsgMetadataResponse *ns5__GetMsgMetadataResponse) { return soap ? soap_call___ns1__getMsgMetadataRequest(soap, endpoint, NULL, ns5__GetMsgMetadataRequest, ns5__GetMsgMetadataResponse) : SOAP_EOM; };
	/// Invoke 'getMsgRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getMsgRequest(ns5__getMsgRequest *ns5__GetMsgRequest, ns5__getMsgResponse *ns5__GetMsgResponse) { return soap ? soap_call___ns1__getMsgRequest(soap, endpoint, NULL, ns5__GetMsgRequest, ns5__GetMsgResponse) : SOAP_EOM; };
	/// Invoke 'getNoteRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getNoteRequest(ns5__getNoteRequest *ns5__GetNoteRequest, ns5__getNoteResponse *ns5__GetNoteResponse) { return soap ? soap_call___ns1__getNoteRequest(soap, endpoint, NULL, ns5__GetNoteRequest, ns5__GetNoteResponse) : SOAP_EOM; };
	/// Invoke 'getNotificationsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getNotificationsRequest(ns5__getNotificationsRequest *ns5__GetNotificationsRequest, ns5__getNotificationsResponse *ns5__GetNotificationsResponse) { return soap ? soap_call___ns1__getNotificationsRequest(soap, endpoint, NULL, ns5__GetNotificationsRequest, ns5__GetNotificationsResponse) : SOAP_EOM; };
	/// Invoke 'getOutgoingFilterRulesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getOutgoingFilterRulesRequest(ns5__getOutgoingFilterRulesRequest *ns5__GetOutgoingFilterRulesRequest, ns5__getOutgoingFilterRulesResponse *ns5__GetOutgoingFilterRulesResponse) { return soap ? soap_call___ns1__getOutgoingFilterRulesRequest(soap, endpoint, NULL, ns5__GetOutgoingFilterRulesRequest, ns5__GetOutgoingFilterRulesResponse) : SOAP_EOM; };
	/// Invoke 'getPermissionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getPermissionRequest(ns5__getPermissionRequest *ns5__GetPermissionRequest, ns5__getPermissionResponse *ns5__GetPermissionResponse) { return soap ? soap_call___ns1__getPermissionRequest(soap, endpoint, NULL, ns5__GetPermissionRequest, ns5__GetPermissionResponse) : SOAP_EOM; };
	/// Invoke 'getRecurRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getRecurRequest(ns5__getRecurRequest *ns5__GetRecurRequest, ns5__getRecurResponse *ns5__GetRecurResponse) { return soap ? soap_call___ns1__getRecurRequest(soap, endpoint, NULL, ns5__GetRecurRequest, ns5__GetRecurResponse) : SOAP_EOM; };
	/// Invoke 'getSearchFolderRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getSearchFolderRequest(ns5__getSearchFolderRequest *ns5__GetSearchFolderRequest, ns5__getSearchFolderResponse *ns5__GetSearchFolderResponse) { return soap ? soap_call___ns1__getSearchFolderRequest(soap, endpoint, NULL, ns5__GetSearchFolderRequest, ns5__GetSearchFolderResponse) : SOAP_EOM; };
	/// Invoke 'getShareDetailsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getShareDetailsRequest(ns5__getShareDetailsRequest *ns5__GetShareDetailsRequest, ns5__getShareDetailsResponse *ns5__GetShareDetailsResponse) { return soap ? soap_call___ns1__getShareDetailsRequest(soap, endpoint, NULL, ns5__GetShareDetailsRequest, ns5__GetShareDetailsResponse) : SOAP_EOM; };
	/// Invoke 'getShareNotificationsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getShareNotificationsRequest(ns5__getShareNotificationsRequest *ns5__GetShareNotificationsRequest, ns5__getShareNotificationsResponse *ns5__GetShareNotificationsResponse) { return soap ? soap_call___ns1__getShareNotificationsRequest(soap, endpoint, NULL, ns5__GetShareNotificationsRequest, ns5__GetShareNotificationsResponse) : SOAP_EOM; };
	/// Invoke 'getSpellDictionariesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getSpellDictionariesRequest(ns5__getSpellDictionariesRequest *ns5__GetSpellDictionariesRequest, ns5__getSpellDictionariesResponse *ns5__GetSpellDictionariesResponse) { return soap ? soap_call___ns1__getSpellDictionariesRequest(soap, endpoint, NULL, ns5__GetSpellDictionariesRequest, ns5__GetSpellDictionariesResponse) : SOAP_EOM; };
	/// Invoke 'getSystemRetentionPolicyRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getSystemRetentionPolicyRequest(ns5__getSystemRetentionPolicyRequest *ns5__GetSystemRetentionPolicyRequest, ns5__getSystemRetentionPolicyResponse *ns5__GetSystemRetentionPolicyResponse) { return soap ? soap_call___ns1__getSystemRetentionPolicyRequest(soap, endpoint, NULL, ns5__GetSystemRetentionPolicyRequest, ns5__GetSystemRetentionPolicyResponse) : SOAP_EOM; };
	/// Invoke 'getTagRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getTagRequest(ns5__getTagRequest *ns5__GetTagRequest, ns5__getTagResponse *ns5__GetTagResponse) { return soap ? soap_call___ns1__getTagRequest(soap, endpoint, NULL, ns5__GetTagRequest, ns5__GetTagResponse) : SOAP_EOM; };
	/// Invoke 'getTaskRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getTaskRequest(ns5__getTaskRequest *ns5__GetTaskRequest, ns5__getTaskResponse *ns5__GetTaskResponse) { return soap ? soap_call___ns1__getTaskRequest(soap, endpoint, NULL, ns5__GetTaskRequest, ns5__GetTaskResponse) : SOAP_EOM; };
	/// Invoke 'getTaskSummariesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getTaskSummariesRequest(ns5__getTaskSummariesRequest *ns5__GetTaskSummariesRequest, ns5__getTaskSummariesResponse *ns5__GetTaskSummariesResponse) { return soap ? soap_call___ns1__getTaskSummariesRequest(soap, endpoint, NULL, ns5__GetTaskSummariesRequest, ns5__GetTaskSummariesResponse) : SOAP_EOM; };
	/// Invoke 'getWatchersRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getWatchersRequest(ns5__getWatchersRequest *ns5__GetWatchersRequest, ns5__getWatchersResponse *ns5__GetWatchersResponse) { return soap ? soap_call___ns1__getWatchersRequest(soap, endpoint, NULL, ns5__GetWatchersRequest, ns5__GetWatchersResponse) : SOAP_EOM; };
	/// Invoke 'getWatchingItemsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getWatchingItemsRequest(ns5__getWatchingItemsRequest *ns5__GetWatchingItemsRequest, ns5__getWatchingItemsResponse *ns5__GetWatchingItemsResponse) { return soap ? soap_call___ns1__getWatchingItemsRequest(soap, endpoint, NULL, ns5__GetWatchingItemsRequest, ns5__GetWatchingItemsResponse) : SOAP_EOM; };
	/// Invoke 'getWorkingHoursRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getWorkingHoursRequest(ns5__getWorkingHoursRequest *ns5__GetWorkingHoursRequest, ns5__getWorkingHoursResponse *ns5__GetWorkingHoursResponse) { return soap ? soap_call___ns1__getWorkingHoursRequest(soap, endpoint, NULL, ns5__GetWorkingHoursRequest, ns5__GetWorkingHoursResponse) : SOAP_EOM; };
	/// Invoke 'getYahooAuthTokenRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getYahooAuthTokenRequest(ns5__getYahooAuthTokenRequest *ns5__GetYahooAuthTokenRequest, ns5__getYahooAuthTokenResponse *ns5__GetYahooAuthTokenResponse) { return soap ? soap_call___ns1__getYahooAuthTokenRequest(soap, endpoint, NULL, ns5__GetYahooAuthTokenRequest, ns5__GetYahooAuthTokenResponse) : SOAP_EOM; };
	/// Invoke 'getYahooCookieRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getYahooCookieRequest(ns5__getYahooCookieRequest *ns5__GetYahooCookieRequest, ns5__getYahooCookieResponse *ns5__GetYahooCookieResponse) { return soap ? soap_call___ns1__getYahooCookieRequest(soap, endpoint, NULL, ns5__GetYahooCookieRequest, ns5__GetYahooCookieResponse) : SOAP_EOM; };
	/// Invoke 'grantPermissionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__grantPermissionRequest(ns5__grantPermissionRequest *ns5__GrantPermissionRequest, ns5__grantPermissionResponse *ns5__GrantPermissionResponse) { return soap ? soap_call___ns1__grantPermissionRequest(soap, endpoint, NULL, ns5__GrantPermissionRequest, ns5__GrantPermissionResponse) : SOAP_EOM; };
	/// Invoke 'iCalReplyRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__iCalReplyRequest(ns5__iCalReplyRequest *ns5__ICalReplyRequest, ns5__iCalReplyResponse *ns5__ICalReplyResponse) { return soap ? soap_call___ns1__iCalReplyRequest(soap, endpoint, NULL, ns5__ICalReplyRequest, ns5__ICalReplyResponse) : SOAP_EOM; };
	/// Invoke 'importAppointmentsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__importAppointmentsRequest(ns5__importAppointmentsRequest *ns5__ImportAppointmentsRequest, ns5__importAppointmentsResponse *ns5__ImportAppointmentsResponse) { return soap ? soap_call___ns1__importAppointmentsRequest(soap, endpoint, NULL, ns5__ImportAppointmentsRequest, ns5__ImportAppointmentsResponse) : SOAP_EOM; };
	/// Invoke 'importContactsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__importContactsRequest(ns5__importContactsRequest *ns5__ImportContactsRequest, ns5__importContactsResponse *ns5__ImportContactsResponse) { return soap ? soap_call___ns1__importContactsRequest(soap, endpoint, NULL, ns5__ImportContactsRequest, ns5__ImportContactsResponse) : SOAP_EOM; };
	/// Invoke 'importDataRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__importDataRequest(ns5__importDataRequest *ns5__ImportDataRequest, ns5__importDataResponse *ns5__ImportDataResponse) { return soap ? soap_call___ns1__importDataRequest(soap, endpoint, NULL, ns5__ImportDataRequest, ns5__ImportDataResponse) : SOAP_EOM; };
	/// Invoke 'invalidateReminderDeviceRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__invalidateReminderDeviceRequest(ns5__invalidateReminderDeviceRequest *ns5__InvalidateReminderDeviceRequest, ns5__invalidateReminderDeviceResponse *ns5__InvalidateReminderDeviceResponse) { return soap ? soap_call___ns1__invalidateReminderDeviceRequest(soap, endpoint, NULL, ns5__InvalidateReminderDeviceRequest, ns5__InvalidateReminderDeviceResponse) : SOAP_EOM; };
	/// Invoke 'itemActionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__itemActionRequest(ns5__itemActionRequest *ns5__ItemActionRequest, ns5__itemActionResponse *ns5__ItemActionResponse) { return soap ? soap_call___ns1__itemActionRequest(soap, endpoint, NULL, ns5__ItemActionRequest, ns5__ItemActionResponse) : SOAP_EOM; };
	/// Invoke 'listDocumentRevisionsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__listDocumentRevisionsRequest(ns5__listDocumentRevisionsRequest *ns5__ListDocumentRevisionsRequest, ns5__listDocumentRevisionsResponse *ns5__ListDocumentRevisionsResponse) { return soap ? soap_call___ns1__listDocumentRevisionsRequest(soap, endpoint, NULL, ns5__ListDocumentRevisionsRequest, ns5__ListDocumentRevisionsResponse) : SOAP_EOM; };
	/// Invoke 'modifyAppointmentRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifyAppointmentRequest(ns5__modifyAppointmentRequest *ns5__ModifyAppointmentRequest, ns5__modifyAppointmentResponse *ns5__ModifyAppointmentResponse) { return soap ? soap_call___ns1__modifyAppointmentRequest(soap, endpoint, NULL, ns5__ModifyAppointmentRequest, ns5__ModifyAppointmentResponse) : SOAP_EOM; };
	/// Invoke 'modifyContactRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifyContactRequest(ns5__modifyContactRequest *ns5__ModifyContactRequest, ns5__modifyContactResponse *ns5__ModifyContactResponse) { return soap ? soap_call___ns1__modifyContactRequest(soap, endpoint, NULL, ns5__ModifyContactRequest, ns5__ModifyContactResponse) : SOAP_EOM; };
	/// Invoke 'modifyDataSourceRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifyDataSourceRequest(ns5__modifyDataSourceRequest *ns5__ModifyDataSourceRequest, ns5__modifyDataSourceResponse *ns5__ModifyDataSourceResponse) { return soap ? soap_call___ns1__modifyDataSourceRequest(soap, endpoint, NULL, ns5__ModifyDataSourceRequest, ns5__ModifyDataSourceResponse) : SOAP_EOM; };
	/// Invoke 'modifyFilterRulesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifyFilterRulesRequest(ns5__modifyFilterRulesRequest *ns5__ModifyFilterRulesRequest, ns5__modifyFilterRulesResponse *ns5__ModifyFilterRulesResponse) { return soap ? soap_call___ns1__modifyFilterRulesRequest(soap, endpoint, NULL, ns5__ModifyFilterRulesRequest, ns5__ModifyFilterRulesResponse) : SOAP_EOM; };
	/// Invoke 'modifyMailboxMetadataRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifyMailboxMetadataRequest(ns5__modifyMailboxMetadataRequest *ns5__ModifyMailboxMetadataRequest, ns5__modifyMailboxMetadataResponse *ns5__ModifyMailboxMetadataResponse) { return soap ? soap_call___ns1__modifyMailboxMetadataRequest(soap, endpoint, NULL, ns5__ModifyMailboxMetadataRequest, ns5__ModifyMailboxMetadataResponse) : SOAP_EOM; };
	/// Invoke 'modifyOutgoingFilterRulesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifyOutgoingFilterRulesRequest(ns5__modifyOutgoingFilterRulesRequest *ns5__ModifyOutgoingFilterRulesRequest, ns5__modifyOutgoingFilterRulesResponse *ns5__ModifyOutgoingFilterRulesResponse) { return soap ? soap_call___ns1__modifyOutgoingFilterRulesRequest(soap, endpoint, NULL, ns5__ModifyOutgoingFilterRulesRequest, ns5__ModifyOutgoingFilterRulesResponse) : SOAP_EOM; };
	/// Invoke 'modifySearchFolderRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifySearchFolderRequest(ns5__modifySearchFolderRequest *ns5__ModifySearchFolderRequest, ns5__modifySearchFolderResponse *ns5__ModifySearchFolderResponse) { return soap ? soap_call___ns1__modifySearchFolderRequest(soap, endpoint, NULL, ns5__ModifySearchFolderRequest, ns5__ModifySearchFolderResponse) : SOAP_EOM; };
	/// Invoke 'modifyTaskRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifyTaskRequest(ns5__modifyTaskRequest *ns5__ModifyTaskRequest, ns5__modifyTaskResponse *ns5__ModifyTaskResponse) { return soap ? soap_call___ns1__modifyTaskRequest(soap, endpoint, NULL, ns5__ModifyTaskRequest, ns5__ModifyTaskResponse) : SOAP_EOM; };
	/// Invoke 'msgActionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__msgActionRequest(ns5__msgActionRequest *ns5__MsgActionRequest, ns5__msgActionResponse *ns5__MsgActionResponse) { return soap ? soap_call___ns1__msgActionRequest(soap, endpoint, NULL, ns5__MsgActionRequest, ns5__MsgActionResponse) : SOAP_EOM; };
	/// Invoke 'noOpRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__noOpRequest(ns5__noOpRequest *ns5__NoOpRequest, ns5__noOpResponse *ns5__NoOpResponse) { return soap ? soap_call___ns1__noOpRequest(soap, endpoint, NULL, ns5__NoOpRequest, ns5__NoOpResponse) : SOAP_EOM; };
	/// Invoke 'noteActionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__noteActionRequest(ns5__noteActionRequest *ns5__NoteActionRequest, ns5__noteActionResponse *ns5__NoteActionResponse) { return soap ? soap_call___ns1__noteActionRequest(soap, endpoint, NULL, ns5__NoteActionRequest, ns5__NoteActionResponse) : SOAP_EOM; };
	/// Invoke 'purgeRevisionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__purgeRevisionRequest(ns5__purgeRevisionRequest *ns5__PurgeRevisionRequest, ns5__purgeRevisionResponse *ns5__PurgeRevisionResponse) { return soap ? soap_call___ns1__purgeRevisionRequest(soap, endpoint, NULL, ns5__PurgeRevisionRequest, ns5__PurgeRevisionResponse) : SOAP_EOM; };
	/// Invoke 'rankingActionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__rankingActionRequest(ns5__rankingActionRequest *ns5__RankingActionRequest, ns5__rankingActionResponse *ns5__RankingActionResponse) { return soap ? soap_call___ns1__rankingActionRequest(soap, endpoint, NULL, ns5__RankingActionRequest, ns5__RankingActionResponse) : SOAP_EOM; };
	/// Invoke 'registerDeviceRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__registerDeviceRequest(ns5__registerDeviceRequest *ns5__RegisterDeviceRequest, ns5__registerDeviceResponse *ns5__RegisterDeviceResponse) { return soap ? soap_call___ns1__registerDeviceRequest(soap, endpoint, NULL, ns5__RegisterDeviceRequest, ns5__RegisterDeviceResponse) : SOAP_EOM; };
	/// Invoke 'removeAttachmentsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__removeAttachmentsRequest(ns5__removeAttachmentsRequest *ns5__RemoveAttachmentsRequest, ns5__removeAttachmentsResponse *ns5__RemoveAttachmentsResponse) { return soap ? soap_call___ns1__removeAttachmentsRequest(soap, endpoint, NULL, ns5__RemoveAttachmentsRequest, ns5__RemoveAttachmentsResponse) : SOAP_EOM; };
	/// Invoke 'revokePermissionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__revokePermissionRequest(ns5__revokePermissionRequest *ns5__RevokePermissionRequest, ns5__revokePermissionResponse *ns5__RevokePermissionResponse) { return soap ? soap_call___ns1__revokePermissionRequest(soap, endpoint, NULL, ns5__RevokePermissionRequest, ns5__RevokePermissionResponse) : SOAP_EOM; };
	/// Invoke 'saveDocumentRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__saveDocumentRequest(ns5__saveDocumentRequest *ns5__SaveDocumentRequest, ns5__saveDocumentResponse *ns5__SaveDocumentResponse) { return soap ? soap_call___ns1__saveDocumentRequest(soap, endpoint, NULL, ns5__SaveDocumentRequest, ns5__SaveDocumentResponse) : SOAP_EOM; };
	/// Invoke 'saveDraftRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__saveDraftRequest(ns5__saveDraftRequest *ns5__SaveDraftRequest, ns5__saveDraftResponse *ns5__SaveDraftResponse) { return soap ? soap_call___ns1__saveDraftRequest(soap, endpoint, NULL, ns5__SaveDraftRequest, ns5__SaveDraftResponse) : SOAP_EOM; };
	/// Invoke 'searchConvRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__searchConvRequest(ns5__searchConvRequest *ns5__SearchConvRequest, ns5__searchConvResponse *ns5__SearchConvResponse) { return soap ? soap_call___ns1__searchConvRequest(soap, endpoint, NULL, ns5__SearchConvRequest, ns5__SearchConvResponse) : SOAP_EOM; };
	/// Invoke 'searchRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__searchRequest(ns5__searchRequest *ns5__SearchRequest, ns5__searchResponse *ns5__SearchResponse) { return soap ? soap_call___ns1__searchRequest(soap, endpoint, NULL, ns5__SearchRequest, ns5__SearchResponse) : SOAP_EOM; };
	/// Invoke 'sendDeliveryReportRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__sendDeliveryReportRequest(ns5__sendDeliveryReportRequest *ns5__SendDeliveryReportRequest, ns5__sendDeliveryReportResponse *ns5__SendDeliveryReportResponse) { return soap ? soap_call___ns1__sendDeliveryReportRequest(soap, endpoint, NULL, ns5__SendDeliveryReportRequest, ns5__SendDeliveryReportResponse) : SOAP_EOM; };
	/// Invoke 'sendInviteReplyRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__sendInviteReplyRequest(ns5__sendInviteReplyRequest *ns5__SendInviteReplyRequest, ns5__sendInviteReplyResponse *ns5__SendInviteReplyResponse) { return soap ? soap_call___ns1__sendInviteReplyRequest(soap, endpoint, NULL, ns5__SendInviteReplyRequest, ns5__SendInviteReplyResponse) : SOAP_EOM; };
	/// Invoke 'sendMsgRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__sendMsgRequest(ns5__sendMsgRequest *ns5__SendMsgRequest, ns5__sendMsgResponse *ns5__SendMsgResponse) { return soap ? soap_call___ns1__sendMsgRequest(soap, endpoint, NULL, ns5__SendMsgRequest, ns5__SendMsgResponse) : SOAP_EOM; };
	/// Invoke 'sendShareNotificationRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__sendShareNotificationRequest(ns5__sendShareNotificationRequest *ns5__SendShareNotificationRequest, ns5__sendShareNotificationResponse *ns5__SendShareNotificationResponse) { return soap ? soap_call___ns1__sendShareNotificationRequest(soap, endpoint, NULL, ns5__SendShareNotificationRequest, ns5__SendShareNotificationResponse) : SOAP_EOM; };
	/// Invoke 'sendVerificationCodeRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__sendVerificationCodeRequest(ns5__sendVerificationCodeRequest *ns5__SendVerificationCodeRequest, ns5__sendVerificationCodeResponse *ns5__SendVerificationCodeResponse) { return soap ? soap_call___ns1__sendVerificationCodeRequest(soap, endpoint, NULL, ns5__SendVerificationCodeRequest, ns5__SendVerificationCodeResponse) : SOAP_EOM; };
	/// Invoke 'setAppointmentRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setAppointmentRequest(ns5__setAppointmentRequest *ns5__SetAppointmentRequest, ns5__setAppointmentResponse *ns5__SetAppointmentResponse) { return soap ? soap_call___ns1__setAppointmentRequest(soap, endpoint, NULL, ns5__SetAppointmentRequest, ns5__SetAppointmentResponse) : SOAP_EOM; };
	/// Invoke 'setCustomMetadataRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setCustomMetadataRequest(ns5__setCustomMetadataRequest *ns5__SetCustomMetadataRequest, ns5__setCustomMetadataResponse *ns5__SetCustomMetadataResponse) { return soap ? soap_call___ns1__setCustomMetadataRequest(soap, endpoint, NULL, ns5__SetCustomMetadataRequest, ns5__SetCustomMetadataResponse) : SOAP_EOM; };
	/// Invoke 'setMailboxMetadataRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setMailboxMetadataRequest(ns5__setMailboxMetadataRequest *ns5__SetMailboxMetadataRequest, ns5__setMailboxMetadataResponse *ns5__SetMailboxMetadataResponse) { return soap ? soap_call___ns1__setMailboxMetadataRequest(soap, endpoint, NULL, ns5__SetMailboxMetadataRequest, ns5__SetMailboxMetadataResponse) : SOAP_EOM; };
	/// Invoke 'setTaskRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setTaskRequest(ns5__setTaskRequest *ns5__SetTaskRequest, ns5__setTaskResponse *ns5__SetTaskResponse) { return soap ? soap_call___ns1__setTaskRequest(soap, endpoint, NULL, ns5__SetTaskRequest, ns5__SetTaskResponse) : SOAP_EOM; };
	/// Invoke 'snoozeCalendarItemAlarmRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__snoozeCalendarItemAlarmRequest(ns5__snoozeCalendarItemAlarmRequest *ns5__SnoozeCalendarItemAlarmRequest, ns5__snoozeCalendarItemAlarmResponse *ns5__SnoozeCalendarItemAlarmResponse) { return soap ? soap_call___ns1__snoozeCalendarItemAlarmRequest(soap, endpoint, NULL, ns5__SnoozeCalendarItemAlarmRequest, ns5__SnoozeCalendarItemAlarmResponse) : SOAP_EOM; };
	/// Invoke 'syncRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__syncRequest(ns5__syncRequest *ns5__SyncRequest, ns5__syncResponse *ns5__SyncResponse) { return soap ? soap_call___ns1__syncRequest(soap, endpoint, NULL, ns5__SyncRequest, ns5__SyncResponse) : SOAP_EOM; };
	/// Invoke 'tagActionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__tagActionRequest(ns5__tagActionRequest *ns5__TagActionRequest, ns5__tagActionResponse *ns5__TagActionResponse) { return soap ? soap_call___ns1__tagActionRequest(soap, endpoint, NULL, ns5__TagActionRequest, ns5__TagActionResponse) : SOAP_EOM; };
	/// Invoke 'testDataSourceRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__testDataSourceRequest(ns5__testDataSourceRequest *ns5__TestDataSourceRequest, ns5__testDataSourceResponse *ns5__TestDataSourceResponse) { return soap ? soap_call___ns1__testDataSourceRequest(soap, endpoint, NULL, ns5__TestDataSourceRequest, ns5__TestDataSourceResponse) : SOAP_EOM; };
	/// Invoke 'updateDeviceStatusRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__updateDeviceStatusRequest(ns5__updateDeviceStatusRequest *ns5__UpdateDeviceStatusRequest, ns5__updateDeviceStatusResponse *ns5__UpdateDeviceStatusResponse) { return soap ? soap_call___ns1__updateDeviceStatusRequest(soap, endpoint, NULL, ns5__UpdateDeviceStatusRequest, ns5__UpdateDeviceStatusResponse) : SOAP_EOM; };
	/// Invoke 'verifyCodeRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__verifyCodeRequest(ns5__verifyCodeRequest *ns5__VerifyCodeRequest, ns5__verifyCodeResponse *ns5__VerifyCodeResponse) { return soap ? soap_call___ns1__verifyCodeRequest(soap, endpoint, NULL, ns5__VerifyCodeRequest, ns5__VerifyCodeResponse) : SOAP_EOM; };
	/// Invoke 'waitSetRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__waitSetRequest(ns5__waitSetRequest *ns5__WaitSetRequest, ns5__waitSetResponse *ns5__WaitSetResponse) { return soap ? soap_call___ns1__waitSetRequest(soap, endpoint, NULL, ns5__WaitSetRequest, ns5__WaitSetResponse) : SOAP_EOM; };
	/// Invoke 'becomeMasterRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__becomeMasterRequest(ns6__becomeMasterRequest *ns6__BecomeMasterRequest, ns6__becomeMasterResponse *ns6__BecomeMasterResponse) { return soap ? soap_call___ns1__becomeMasterRequest(soap, endpoint, NULL, ns6__BecomeMasterRequest, ns6__BecomeMasterResponse) : SOAP_EOM; };
	/// Invoke 'bringDownServiceIPRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__bringDownServiceIPRequest(ns6__bringDownServiceIPRequest *ns6__BringDownServiceIPRequest, ns6__bringDownServiceIPResponse *ns6__BringDownServiceIPResponse) { return soap ? soap_call___ns1__bringDownServiceIPRequest(soap, endpoint, NULL, ns6__BringDownServiceIPRequest, ns6__BringDownServiceIPResponse) : SOAP_EOM; };
	/// Invoke 'bringUpServiceIPRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__bringUpServiceIPRequest(ns6__bringUpServiceIPRequest *ns6__BringUpServiceIPRequest, ns6__bringUpServiceIPResponse *ns6__BringUpServiceIPResponse) { return soap ? soap_call___ns1__bringUpServiceIPRequest(soap, endpoint, NULL, ns6__BringUpServiceIPRequest, ns6__BringUpServiceIPResponse) : SOAP_EOM; };
	/// Invoke 'replicationStatusRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__replicationStatusRequest(ns6__replicationStatusRequest *ns6__ReplicationStatusRequest, ns6__replicationStatusResponse *ns6__ReplicationStatusResponse) { return soap ? soap_call___ns1__replicationStatusRequest(soap, endpoint, NULL, ns6__ReplicationStatusRequest, ns6__ReplicationStatusResponse) : SOAP_EOM; };
	/// Invoke 'startCatchupRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__startCatchupRequest(ns6__startCatchupRequest *ns6__StartCatchupRequest, ns6__startCatchupResponse *ns6__StartCatchupResponse) { return soap ? soap_call___ns1__startCatchupRequest(soap, endpoint, NULL, ns6__StartCatchupRequest, ns6__StartCatchupResponse) : SOAP_EOM; };
	/// Invoke 'startFailoverClientRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__startFailoverClientRequest(ns6__startFailoverClientRequest *ns6__StartFailoverClientRequest, ns6__startFailoverClientResponse *ns6__StartFailoverClientResponse) { return soap ? soap_call___ns1__startFailoverClientRequest(soap, endpoint, NULL, ns6__StartFailoverClientRequest, ns6__StartFailoverClientResponse) : SOAP_EOM; };
	/// Invoke 'startFailoverDaemonRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__startFailoverDaemonRequest(ns6__startFailoverDaemonRequest *ns6__StartFailoverDaemonRequest, ns6__startFailoverDaemonResponse *ns6__StartFailoverDaemonResponse) { return soap ? soap_call___ns1__startFailoverDaemonRequest(soap, endpoint, NULL, ns6__StartFailoverDaemonRequest, ns6__StartFailoverDaemonResponse) : SOAP_EOM; };
	/// Invoke 'stopFailoverClientRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__stopFailoverClientRequest(ns6__stopFailoverClientRequest *ns6__StopFailoverClientRequest, ns6__stopFailoverClientResponse *ns6__StopFailoverClientResponse) { return soap ? soap_call___ns1__stopFailoverClientRequest(soap, endpoint, NULL, ns6__StopFailoverClientRequest, ns6__StopFailoverClientResponse) : SOAP_EOM; };
	/// Invoke 'stopFailoverDaemonRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__stopFailoverDaemonRequest(ns6__stopFailoverDaemonRequest *ns6__StopFailoverDaemonRequest, ns6__stopFailoverDaemonResponse *ns6__StopFailoverDaemonResponse) { return soap ? soap_call___ns1__stopFailoverDaemonRequest(soap, endpoint, NULL, ns6__StopFailoverDaemonRequest, ns6__StopFailoverDaemonResponse) : SOAP_EOM; };
	/// Invoke 'cancelPendingRemoteWipeRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__cancelPendingRemoteWipeRequest(ns7__cancelPendingRemoteWipeRequest *ns7__CancelPendingRemoteWipeRequest, ns7__cancelPendingRemoteWipeResponse *ns7__CancelPendingRemoteWipeResponse) { return soap ? soap_call___ns1__cancelPendingRemoteWipeRequest(soap, endpoint, NULL, ns7__CancelPendingRemoteWipeRequest, ns7__CancelPendingRemoteWipeResponse) : SOAP_EOM; };
	/// Invoke 'getDeviceStatusRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getDeviceStatusRequest(ns7__getDeviceStatusRequest *ns7__GetDeviceStatusRequest, ns7__getDeviceStatusResponse *ns7__GetDeviceStatusResponse) { return soap ? soap_call___ns1__getDeviceStatusRequest(soap, endpoint, NULL, ns7__GetDeviceStatusRequest, ns7__GetDeviceStatusResponse) : SOAP_EOM; };
	/// Invoke 'remoteWipeRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__remoteWipeRequest(ns7__remoteWipeRequest *ns7__RemoteWipeRequest, ns7__remoteWipeResponse *ns7__RemoteWipeResponse) { return soap ? soap_call___ns1__remoteWipeRequest(soap, endpoint, NULL, ns7__RemoteWipeRequest, ns7__RemoteWipeResponse) : SOAP_EOM; };
	/// Invoke 'removeDeviceRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__removeDeviceRequest(ns7__removeDeviceRequest *ns7__RemoveDeviceRequest, ns7__removeDeviceResponse *ns7__RemoveDeviceResponse) { return soap ? soap_call___ns1__removeDeviceRequest(soap, endpoint, NULL, ns7__RemoveDeviceRequest, ns7__RemoveDeviceResponse) : SOAP_EOM; };
	/// Invoke 'resumeDeviceRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__resumeDeviceRequest(ns7__resumeDeviceRequest *ns7__ResumeDeviceRequest, ns7__resumeDeviceResponse *ns7__ResumeDeviceResponse) { return soap ? soap_call___ns1__resumeDeviceRequest(soap, endpoint, NULL, ns7__ResumeDeviceRequest, ns7__ResumeDeviceResponse) : SOAP_EOM; };
	/// Invoke 'suspendDeviceRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__suspendDeviceRequest(ns7__suspendDeviceRequest *ns7__SuspendDeviceRequest, ns7__suspendDeviceResponse *ns7__SuspendDeviceResponse) { return soap ? soap_call___ns1__suspendDeviceRequest(soap, endpoint, NULL, ns7__SuspendDeviceRequest, ns7__SuspendDeviceResponse) : SOAP_EOM; };
	/// Invoke 'changeUCPasswordRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__changeUCPasswordRequest(ns8__changeUCPasswordRequest *ns8__ChangeUCPasswordRequest, ns8__changeUCPasswordResponse *ns8__ChangeUCPasswordResponse) { return soap ? soap_call___ns1__changeUCPasswordRequest(soap, endpoint, NULL, ns8__ChangeUCPasswordRequest, ns8__ChangeUCPasswordResponse) : SOAP_EOM; };
	/// Invoke 'getUCInfoRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getUCInfoRequest(ns8__getUCInfoRequest *ns8__GetUCInfoRequest, ns8__getUCInfoResponse *ns8__GetUCInfoResponse) { return soap ? soap_call___ns1__getUCInfoRequest(soap, endpoint, NULL, ns8__GetUCInfoRequest, ns8__GetUCInfoResponse) : SOAP_EOM; };
	/// Invoke 'getVoiceFeaturesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getVoiceFeaturesRequest(ns8__getVoiceFeaturesRequest *ns8__GetVoiceFeaturesRequest, ns8__getVoiceFeaturesResponse *ns8__GetVoiceFeaturesResponse) { return soap ? soap_call___ns1__getVoiceFeaturesRequest(soap, endpoint, NULL, ns8__GetVoiceFeaturesRequest, ns8__GetVoiceFeaturesResponse) : SOAP_EOM; };
	/// Invoke 'getVoiceFolderRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getVoiceFolderRequest(ns8__getVoiceFolderRequest *ns8__GetVoiceFolderRequest, ns8__getVoiceFolderResponse *ns8__GetVoiceFolderResponse) { return soap ? soap_call___ns1__getVoiceFolderRequest(soap, endpoint, NULL, ns8__GetVoiceFolderRequest, ns8__GetVoiceFolderResponse) : SOAP_EOM; };
	/// Invoke 'getVoiceInfoRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getVoiceInfoRequest(ns8__getVoiceInfoRequest *ns8__GetVoiceInfoRequest, ns8__getVoiceInfoResponse *ns8__GetVoiceInfoResponse) { return soap ? soap_call___ns1__getVoiceInfoRequest(soap, endpoint, NULL, ns8__GetVoiceInfoRequest, ns8__GetVoiceInfoResponse) : SOAP_EOM; };
	/// Invoke 'getVoiceMailPrefsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getVoiceMailPrefsRequest(ns8__getVoiceMailPrefsRequest *ns8__GetVoiceMailPrefsRequest, ns8__getVoiceMailPrefsResponse *ns8__GetVoiceMailPrefsResponse) { return soap ? soap_call___ns1__getVoiceMailPrefsRequest(soap, endpoint, NULL, ns8__GetVoiceMailPrefsRequest, ns8__GetVoiceMailPrefsResponse) : SOAP_EOM; };
	/// Invoke 'modifyFromNumRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifyFromNumRequest(ns8__modifyFromNumRequest *ns8__ModifyFromNumRequest, ns8__modifyFromNumResponse *ns8__ModifyFromNumResponse) { return soap ? soap_call___ns1__modifyFromNumRequest(soap, endpoint, NULL, ns8__ModifyFromNumRequest, ns8__ModifyFromNumResponse) : SOAP_EOM; };
	/// Invoke 'modifyVoiceFeaturesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifyVoiceFeaturesRequest(ns8__modifyVoiceFeaturesRequest *ns8__ModifyVoiceFeaturesRequest, ns8__modifyVoiceFeaturesResponse *ns8__ModifyVoiceFeaturesResponse) { return soap ? soap_call___ns1__modifyVoiceFeaturesRequest(soap, endpoint, NULL, ns8__ModifyVoiceFeaturesRequest, ns8__ModifyVoiceFeaturesResponse) : SOAP_EOM; };
	/// Invoke 'modifyVoiceMailPinRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifyVoiceMailPinRequest(ns8__modifyVoiceMailPinRequest *ns8__ModifyVoiceMailPinRequest, ns8__modifyVoiceMailPinResponse *ns8__ModifyVoiceMailPinResponse) { return soap ? soap_call___ns1__modifyVoiceMailPinRequest(soap, endpoint, NULL, ns8__ModifyVoiceMailPinRequest, ns8__ModifyVoiceMailPinResponse) : SOAP_EOM; };
	/// Invoke 'modifyVoiceMailPrefsRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__modifyVoiceMailPrefsRequest(ns8__modifyVoiceMailPrefsRequest *ns8__ModifyVoiceMailPrefsRequest, ns8__modifyVoiceMailPrefsResponse *ns8__ModifyVoiceMailPrefsResponse) { return soap ? soap_call___ns1__modifyVoiceMailPrefsRequest(soap, endpoint, NULL, ns8__ModifyVoiceMailPrefsRequest, ns8__ModifyVoiceMailPrefsResponse) : SOAP_EOM; };
	/// Invoke 'resetVoiceFeaturesRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__resetVoiceFeaturesRequest(ns8__resetVoiceFeaturesRequest *ns8__ResetVoiceFeaturesRequest, ns8__resetVoiceFeaturesResponse *ns8__ResetVoiceFeaturesResponse) { return soap ? soap_call___ns1__resetVoiceFeaturesRequest(soap, endpoint, NULL, ns8__ResetVoiceFeaturesRequest, ns8__ResetVoiceFeaturesResponse) : SOAP_EOM; };
	/// Invoke 'searchVoiceRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__searchVoiceRequest(ns8__searchVoiceRequest *ns8__SearchVoiceRequest, ns8__searchVoiceResponse *ns8__SearchVoiceResponse) { return soap ? soap_call___ns1__searchVoiceRequest(soap, endpoint, NULL, ns8__SearchVoiceRequest, ns8__SearchVoiceResponse) : SOAP_EOM; };
	/// Invoke 'uploadVoiceMailRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__uploadVoiceMailRequest(ns8__uploadVoiceMailRequest *ns8__UploadVoiceMailRequest, ns8__uploadVoiceMailResponse *ns8__UploadVoiceMailResponse) { return soap ? soap_call___ns1__uploadVoiceMailRequest(soap, endpoint, NULL, ns8__UploadVoiceMailRequest, ns8__UploadVoiceMailResponse) : SOAP_EOM; };
	/// Invoke 'voiceMsgActionRequest' of service 'zcsPortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__voiceMsgActionRequest(ns8__voiceMsgActionRequest *ns8__VoiceMsgActionRequest, ns8__voiceMsgActionResponse *ns8__VoiceMsgActionResponse) { return soap ? soap_call___ns1__voiceMsgActionRequest(soap, endpoint, NULL, ns8__VoiceMsgActionRequest, ns8__VoiceMsgActionResponse) : SOAP_EOM; };
};
#endif
